<?xml version="1.0" encoding="UTF-8"?>
<!--
Коренът ни е channel, който съдържа задължителни елементи item, title, link и description; image и language не са.
За поделементите на item и image трябваше да се извъртят пермутациите, тъй като нямат определена последователност.
Тъй като item и image се срещат много пъти, имат квантори в зависимост от това дали са задължителни (+) или не (*).
Останалото е тривиално.
-->
<!DOCTYPE channel [
<!ELEMENT channel (item+ , title , link , image* , language? , description)>
<!ELEMENT item ((title , ((link , description?) | (description? , link))) | (link , ((title , description?) | (description? , title))) | (description? , ((title , link) | (link , title))))>
<!ELEMENT title (#PCDATA)>
<!ELEMENT link (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image ((title , ((link , url) | (url , link))) | (link , ((title , url) | (url , title))) | (url , ((title , link) | (link , title))))>
<!ELEMENT url (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ATTLIST channel version CDATA #IMPLIED>
]>
<channel version="0.1">
  <item>
    <title>BNT1</title>
    <link><![CDATA[https://bnt1.bnt.bg/]]></link>
  </item>
  <item>
    <link><![CDATA[https://bnt2.bnt.bg/]]></link>
    <description>Българска национална телевизия, канал 2.</description>
    <title>BNT2</title>
  </item>
  <title>BNT</title>
  <link><![CDATA[https://bnt.bg/]]></link>
  <image>
    <title>BNT1 Shows</title>
    <link>Show BNT1 shows</link>
    <url><![CDATA[https://bnt.bg/box/img/BNT1.svg]]></url>
  </image>
  <image>
    <link>Go to homepage.</link>
    <title>BNT Homepage</title>
    <url><![CDATA[https://bnt.bg/box/img/wlogo.svg]]></url>
  </image>
  <language>BG</language>
  <description>Българската национална телевизия (БНТ) е обществената телевизия в България. Открита е официално на 26 декември 1959 г. в резултат от осемгодишна разработка и изпитания на екип от учени от Машинно-електротехническия институт в София.</description>
</channel>
