<?xml version="1.0"?>
<!--
Имаме корен games, който съдържа една или повече игри (game+).
Играта е съставена от два отбора (home-team & ex-team), резултати (scores) и играчи, получили жълти/червени картони (yellows & reds).
Home-team и ex-team представляват имената на отборите, затова са просто PCDATA.
Scores съдържа неопределен брой попадения (score*). Всеки score съдържа името на извършителя (player).
Yellows и reds съдържат нула или повече играчи.
Елементът game има атрибут score, който се предполага, че е задължителен, със стойност CDATA.
Елементът score има атрибути me (като id, може да е CDATA или NMTOKEN) и type (не е задължителен, CDATA).
-->
<!DOCTYPE games [
<!ELEMENT games (game+)>
<!ELEMENT game (home-team , ex-team , scores , yellows , reds)>
<!ELEMENT home-team (#PCDATA)>
<!ELEMENT ex-team (#PCDATA)>
<!ELEMENT scores (score*)>
<!ELEMENT score (player)>
<!ELEMENT player (#PCDATA)>
<!ELEMENT yellows (player*)>
<!ELEMENT reds (player*)>
<!ATTLIST game score CDATA #REQUIRED>
<!ATTLIST score me CDATA #REQUIRED>
<!ATTLIST score type CDATA #IMPLIED>
]>
<games>
  <game score="1-1">
    <home-team>Roma</home-team>
    <ex-team>Lazio</ex-team>
    <scores>
      <score me="15">
        <player>Klose</player>
      </score>
      <score me="85" type="penalty">
        <player>Tox</player>
      </score>
    </scores>
    <yellows>
      <player>Tox</player>
      <player>Hernanes</player>
    </yellows>
    <reds>
      <player>Kjaer</player>
    </reds>
  </game>
</games>
